name: Build NG-GL4ES for Android

on:
  push:
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
    - uses: actions/checkout@v4

    - name: Setup Android NDK
      uses: android-actions/setup-android-ndk@v2
      with:
        ndk-version: latest
    
    - name: Configure CMake
      run: |
        cmake -B build \
        -DANDROID_ABI=arm64-v8a \
        -DANDROID_PLATFORM=android-29 \
        -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake \
        -DANDROID_TOOLCHAIN=clang

    - name: Build
      run: cmake --build build --config Release --parallel $(nproc)

    - name: Strip
      run: |
        cd build
        $ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip libng_gl4es.so
        
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: NG-GL4ES
        path: build/libng_gl4es.so
